# Change these first
owner: pxlbuzzard # Your GitHub username
repo: upptime # Your GitHub repository name
user-agent: pxlbuzzard

# Add your sites here
sites:
  - name: Daniel Jost
    url: https://danieljost.com

  - name: ArchiveBox
    url: https://archivebox.pxlbuzzard.com
  - name: Gitea
    url: https://git.pxlbuzzard.com
  - name: Home Assistant
    url: https://homeassistant.pxlbuzzard.com
  - name: Overseerr
    url: https://request.pxlbuzzard.com
  - name: Plex
    url: https://plex.pxlbuzzard.com
  - name: XBackBone
    url: https://share.pxlbuzzard.com

  - name: Terris Top Treatments
    url: https://terristoptreatments.com
#   - name: K. J. Kamphoefner Design
#     url: https://kjkamphoefnerdesign.com
  - name: Luann Spencer Steele
    url: https://luannspencersteele.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.pxlbuzzard.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PxlBuzzard Status Page
  introTitle: "PxlBuzzard does websites for a living."
  introMessage: Upptime is tracking these self-hosted and work sites for me, which is p neat.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/pxlbuzzard/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees:
  - PxlBuzzard
